=== CsiszerCsongor/xml_validator/xml_documents/document.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:element name="legaldocument">
		<!-- XSC validation rules -->
		<xs:complexType>
			<xs:sequence>
				<xs:element name="dokumentumCim">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="200"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="dokumentumSzovegesSzama">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="0"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="dokumentumEvszama">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="1900"/>
							<xs:maxInclusive value="2100"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="dokumentumSorszama">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="0"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="dokumentumTipusa">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="COM"/>
							<xs:enumeration value="JOIN"/>
							<xs:enumeration value="SEC"/>
							<xs:enumeration value="SWD"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="kibocsatoKod">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="EB"/>
							<xs:enumeration value="fk"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="kibocsatasDatuma">
					<xs:simpleType>
						<xs:restriction base="xs:date">
							<xs:minInclusive value="1900-01-01"/>
							<xs:maxInclusive value="2100-01-01"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="dokumentumTartalom">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="szakasz" type="szakaszType" minOccurs="1" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="szakaszType">
		<xs:sequence>
			<xs:element name="bekezdes" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>

=== CsiszerCsongor/xml_validator/document_valid_03.xml
<?xml version="1.0" encoding="UTF-8" ?>
<legaldocument	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				xsi:noNamespaceSchemaLocation="document.xsd">
	
	<dokumentumCim>European Union Research Council (ERC) - version 3.0</dokumentumCim>
	<dokumentumSzovegesSzama>10</dokumentumSzovegesSzama>
	<dokumentumEvszama>2020</dokumentumEvszama>
	<dokumentumSorszama>0</dokumentumSorszama>
	<dokumentumTipusa>SEC</dokumentumTipusa>
	<kibocsatoKod>EB</kibocsatoKod>
	<kibocsatasDatuma>2020-08-03</kibocsatasDatuma>
	<dokumentumTartalom>
		<szakasz>
			<bekezdes>The costs of renting or leasing equipment, infrastructure or other assets (including related
duties, taxes and charges such as non-deductible value added tax (VAT) paid by the
beneficiary) are also eligible, if they do not exceed the depreciation costs of similar
equipment, infrastructure or assets and do not include any financing fees. </bekezdes>
			<bekezdes>The costs of equipment, infrastructure or other assets contributed in-kind against payment
are eligible, if they do not exceed the depreciation costs of similar equipment, infrastructure
or assets, do not include any financing fees and if the conditions in Article 11.1 are met</bekezdes>
			<bekezdes>The only portion of the costs that will be taken into account is that which corresponds to the
duration of the action and rate of actual use for the purposes of the action.]</bekezdes>
		</szakasz>
		<szakasz>
			<bekezdes>The cost of purchasing equipment, infrastructure or other assets (new or second-hand) (as
recorded in the beneficiaryâ€™s accounts) are eligible if the equipment, infrastructure or other
assets was purchased in accordance with Article 10.1.1. </bekezdes>
			<bekezdes>The costs of renting or leasing equipment, infrastructure or other assets (including related
duties, taxes and charges such as non-deductible value added tax (VAT) paid by the
beneficiary) are also eligible, if they do not exceed the depreciation costs of similar
equipment, infrastructure or assets and do not include any financing fees.</bekezdes>
			<bekezdes>The costs of equipment, infrastructure or other assets contributed in-kind against payment
are eligible, if they do not exceed the depreciation costs of similar equipment, infrastructure
or assets, do not include any financing fees and if the conditions in Article 11.1 are met.</bekezdes>
		</szakasz>
	</dokumentumTartalom>
</legaldocument>
